### ISSUE TITLE
i have a question

### ISSUE THREAD

**Issue by kamilisa** [dgovil/MLDeform#1]
maya python version is 2.7.11
but pandas need numpy 1.3 or above...
tensorflow need python 3.5 or above..
so, i can't use maya running  ‘’from MLDeform import train ‘’
happen a error...
because maya can't import pandas and tensorflow

**Comment by dgovil** [comment]
Hi,
You should be able to get Tensorflow for Python 2.7. https://www.tensorflow.org/install/

You may need to get an older version of tensorflow depending on your OS because it looks like they are now requiring 3.5+ for Windows, but they still support 2.7 for macOS.

I just used ana**conda** to install tensorflow, and then I added the anaconda library paths to my Maya library paths.

**Comment by kamilisa** [comment]
oh, that's too bad, i'm windows 10

**Comment by deniceH** [comment]
hello dhruv,
I'm an animation student and I'll really like to test your great implementation with my rigs. I started to work with linux (unfortunately there's no mac available) but I was not able to import tensorflow into maya until now. I installed tensorflow with anaconda in a virtual environment and added a pythonpath variable to the maya.env file pointing to the bin folder of the virtual environment.
Could you specify how you added the anaconda library paths to the maya library paths?
Thank you for your help!
Best, Denise

**Comment by syedharoonalam** [comment]
@dgovil I am facing the same error 
Can you please elaborate where is the anaconda library path?
(C:\ProgramData\Anaconda3\Lib?)

Also what variable in Maya.env should I change?

Thank you
